version: "3.7"
services:
  # db:
  #   image: "mysql:5.7"
  #   restart: always
  #   environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_USERNAME: root
  #    MYSQL_PASSWORD: root
  #       - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - ./db_data:/var/lib/mysql
  #   logging:
  #     driver: none
  #   ports:
  #     - "3306:3306"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
          - '3306:3306'
    expose:
      - '3306'
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none
  web:
    build: .
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_NAME: ecs_application_db
     DB_PORT: 3306
     DB_HOST: mysql
     RAILS_ENV: development
     RAILS_MAX_THREADS: 5
     REDIS_HOST: redis
     REDIS_PORT: 6379
     BUNDLE_PATH: /bundle
    volumes:
      - .:/rails-app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "mysql"
      - "redis"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails-app
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - "redis"
volumes:
  dbdata:
  bundle:
  redis: